apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd-dockerhub-egress
  namespace: argocd
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  egress:
    - toFQDNs:
        - matchPattern: "*.docker.io"
        - matchName: "production.cloudflare.docker.com"
        - matchName: "docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP